alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED

features:
  - buildpack-stack=ubuntu-22

name: cadastro-voluntarias-staging
region: atl

services:
  - name: nossas-mapa-org-formularios
    http_port: 8000
    image:
      registry: nossas
      registry_type: DOCKER_HUB
      repository: mapa-org-formularios
      tag: PLACEHOLDER_TAG
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
