name: cadastro-voluntarias-staging
region: atl
features:
  - buildpack-stack=ubuntu-22

alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED

services:
  - name: nossas-mapa-org-formularios
    http_port: 8000
    image:
      registry: docker.io
      registry_type: DOCKER_HUB
      repository: nossas/mapa-org-formularios
      tag: PLACEHOLDER_TAG
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb