name: Deploy to DigitalOcean Staging

on:
  pull_request:
    branches:
      - "**"

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
    needs: build
    name: Deploy
    runs-on: ubuntu-latest

    env:
      DEBUG: ${{ vars.DEBUG }}
      ALLOWED_HOSTS: ${{ vars.STG_ALLOWED_HOSTS }}
      MSR_HOST: ${{ vars.STG_MSR_HOST }}
      VOLUNTEER_HOST: ${{ vars.STG_VOLUNTEER_HOST }}
      DOCKER_CREDENTIALS: ${{ secrets.REGISTRY_CREDENTIALS_DOCKER }}
      BONDE_DATABASE_URL: ${{ secrets.STG_BONDE_DATABASE_URL }}
      MOODLE_API_URL: ${{ secrets.MOODLE_API_URL }}
      MOODLE_API_KEY: ${{ secrets.MOODLE_API_KEY }}
      MOODLE_DATABASE_URL: ${{ secrets.MOODLE_DATABASE_URL }}
      MOODLE_DEFAULT_PASS: ${{ secrets.MOODLE_DEFAULT_PASS }}
      GEOCODING_API_KEY: ${{ secrets.GEOCODING_API_KEY }}
      GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
      LOOPS_API_KEY: ${{ secrets.LOOPS_API_KEY }}
      META_PIXEL_ID: ${{ secrets.META_PIXEL_ID }}
      ZENDESK_SUBDOMAIN: ${{ secrets.ZENDESK_SUBDOMAIN }}
      ZENDESK_API_TOKEN: ${{ secrets.ZENDESK_API_TOKEN }}
      ZENDESK_API_USER: ${{ secrets.ZENDESK_API_USER }}
      NEW_RELIC_LICENSE_KEY: ${{ secrets.NEW_RELIC_LICENSE_KEY }}
      STG_BONDE_DATABASE_URL: ${{ secrets.STG_BONDE_DATABASE_URL }}
      STG_MAPA_DATABASE_URL: ${{ secrets.STG_MAPA_DATABASE_URL }}
      CADASTRO_VOLUNTARIAS_APP_ID: ${{ secrets.CADASTRO_VOLUNTARIAS_APP_ID }}
     
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Definir IMAGE_TAG
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "IMAGE_TAG=pr-${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=${{ github.ref_name }}" >> $GITHUB_ENV
          fi

      - name: Carregar secrets no ambiente
        run: |
          echo "DOCKER_IMAGE=nossas/mapa-org-formularios:${IMAGE_TAG}" >> $GITHUB_ENV
          echo "DOCKER_CREDENTIALS=${REGISTRY_CREDENTIALS_DOCKER}" >> $GITHUB_ENV
          echo "DATABASE_URL=${STG_MAPA_DATABASE_URL}" >> $GITHUB_ENV
          echo "BONDE_DATABASE_URL=${STG_BONDE_DATABASE_URL}" >> $GITHUB_ENV
          echo "MOODLE_API_URL=${MOODLE_API_URL}" >> $GITHUB_ENV
          echo "MOODLE_API_KEY=${MOODLE_API_KEY}" >> $GITHUB_ENV
          echo "MOODLE_DATABASE_URL=${MOODLE_DATABASE_URL}" >> $GITHUB_ENV
          echo "MOODLE_DEFAULT_PASS=${MOODLE_DEFAULT_PASS}" >> $GITHUB_ENV
          echo "GEOCODING_API_KEY=${GEOCODING_API_KEY}" >> $GITHUB_ENV
          echo "GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}" >> $GITHUB_ENV
          echo "LOOPS_API_KEY=${LOOPS_API_KEY}" >> $GITHUB_ENV
          echo "META_PIXEL_ID=${META_PIXEL_ID}" >> $GITHUB_ENV
          echo "ZENDESK_SUBDOMAIN=${ZENDESK_SUBDOMAIN}" >> $GITHUB_ENV
          echo "ZENDESK_API_TOKEN=${ZENDESK_API_TOKEN}" >> $GITHUB_ENV
          echo "ZENDESK_API_USER=${ZENDESK_API_USER}" >> $GITHUB_ENV
          echo "NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}" >> $GITHUB_ENV
          echo "NEW_RELIC_ENVIRONMENT=staging" >> $GITHUB_ENV

      - name: Atualizar app.yaml com tag e credenciais
        run: |
          sed -i "s|PLACEHOLDER_TAG|${IMAGE_TAG}|g" ./deploy/app.yaml
          sed -i "s|REGISTRY_CREDENTIALS_ID_PLACEHOLDER|${DOCKER_CREDENTIALS}|g" ./deploy/app.yaml

      - name: Substituir variáveis no app.yaml
        run: |
          sudo apt-get update && sudo apt-get install -y gettext-base
          envsubst < ./deploy/app.yaml > ./deploy/app_resolved.yaml
          echo "Arquivo resolvido:"
          head -n 20 ./deploy/app_resolved.yaml  # só pra debug visual no log

      - name: Instalar doctl
        # v2.4.0 - https://github.com/digitalocean/action-doctl/releases/tag/v2.4.0
        uses: digitalocean/action-doctl@595d91dabf2c6f9194ba08393311cba86e45b6ae

        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Aplicar spec na App Platform
        run: doctl apps update ${CADASTRO_VOLUNTARIAS_APP_ID} --spec ./deploy/app_resolved.yaml