name: Deploy to DigitalOcean Staging
on:
  pull_request:
    branches:
      - "**"

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
    needs:
      - build
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Definir IMAGE_TAG
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "IMAGE_TAG=pr-${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=${{ github.ref_name }}" >> $GITHUB_ENV
          fi
      - name: Preencher envs no app.yaml
        run: |
          echo "DOCKER_IMAGE=nossas/mapa-org-formularios:${IMAGE_TAG}" >> $GITHUB_ENV
          echo "ALLOWED_HOSTS=${{ vars.STG_ALLOWED_HOSTS }}" >> $GITHUB_ENV
          echo "DATABASE_URL=${{ secrets.STG_MAPA_DATABASE_URL }}" >> $GITHUB_ENV
          echo "BONDE_DATABASE_URL=${{ secrets.STG_BONDE_DATABASE_URL }}" >> $GITHUB_ENV
          echo "DEBUG=${{ vars.DEBUG }}" >> $GITHUB_ENV
          echo "MOODLE_API_URL=${{ secrets.MOODLE_API_URL }}" >> $GITHUB_ENV
          echo "MOODLE_API_KEY=${{ secrets.MOODLE_API_KEY }}" >> $GITHUB_ENV
          echo "MSR_HOST=${{ vars.STG_MSR_HOST }}" >> $GITHUB_ENV
          echo "VOLUNTEER_HOST=${{ vars.STG_VOLUNTEER_HOST }}" >> $GITHUB_ENV
          echo "GEOCODING_API_KEY=${{ secrets.GEOCODING_API_KEY }}" >> $GITHUB_ENV
          echo "GOOGLE_MAPS_API_KEY=${{ secrets.GOOGLE_MAPS_API_KEY }}" >> $GITHUB_ENV
          echo "MOODLE_DATABASE_URL=${{ secrets.MOODLE_DATABASE_URL }}" >> $GITHUB_ENV
          echo "LOOPS_API_KEY=${{ secrets.LOOPS_API_KEY }}" >> $GITHUB_ENV
          echo "ZENDESK_SUBDOMAIN=${{ secrets.ZENDESK_SUBDOMAIN }}" >> $GITHUB_ENV
          echo "ZENDESK_API_TOKEN=${{ secrets.ZENDESK_API_TOKEN }}" >> $GITHUB_ENV
          echo "ZENDESK_API_USER=${{ secrets.ZENDESK_API_USER }}" >> $GITHUB_ENV
          echo "MOODLE_DEFAULT_PASS=${{ secrets.MOODLE_DEFAULT_PASS }}" >> $GITHUB_ENV
          echo "META_PIXEL_ID=${{ secrets.META_PIXEL_ID }}" >> $GITHUB_ENV
  
      - name: Update app.yaml with new tag
        run: |
          sed -i "s|PLACEHOLDER_TAG|${IMAGE_TAG}|g" ./deploy/app.yaml
          sed -i "s|REGISTRY_CREDENTIALS_ID_PLACEHOLDER|${{ secrets.REGISTRY_CREDENTIALS_DOCKER }}|g" ./deploy/app.yaml
     
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Apply new spec to App Platform
        run: doctl apps update ${{ secrets.CADASTRO_VOLUNTARIAS_APP_ID }} --spec ./deploy/app.yaml